name: Varbase Internationalization Base
description: A recipe to manage internationalization, languages, and translation support with default configurations and permissions for Varbase multilingual sites.
type: Varbase Internationalization
install:
  - language
  - locale
  - config_translation
  - content_translation
  - eca
  - eca_language
config:
  actions:
    language.content_settings.canvas_page.canvas_page:
      createIfNotExists:
        target_entity_type_id: canvas_page
        target_bundle: canvas_page
        default_langcode: site_default
        language_alterable: false
        third_party_settings:
          content_translation:
            enabled: true
            bundle_settings:
              untranslatable_fields_hide: '0'
      setProperties:
        third_party_settings:
          content_translation:
            enabled: true
            bundle_settings:
              untranslatable_fields_hide: '0'
    core.base_field_override.canvas_page.canvas_page.components:
      createIfNotExists:
        field_name: components
        entity_type: canvas_page
        bundle: canvas_page
        label: Components
        description: ''
        required: false
        translatable: true
        default_value: {  }
        default_value_callback: ''
        settings: {  }
        field_type: component_tree
        third_party_settings:
          content_translation:
            translation_sync:
              inputs: inputs
              tree: '0'
      setProperties:
        translatable: true
    user.role.content_editor:
      grantPermissions:
        - 'create content translations'
        - 'update content translations'
        - 'translate any entity'
    user.role.content_admin:
      grantPermissions:
        - 'create content translations'
        - 'delete content translations'
        - 'update content translations'
        - 'translate any entity'
    user.role.seo_admin:
      grantPermissions:
        - 'create content translations'
        - 'update content translations'
        - 'translate any entity'
    user.role.site_admin:
      grantPermissions:
        - 'create content translations'
        - 'delete content translations'
        - 'update content translations'
        - 'translate any entity'
