name: Varbase Internationalization Base
description: A recipe to manage internationalization, languages, and translation support with default configurations and permissions for Varbase multilingual sites.
type: Varbase Internationalization
install:
  - language
  - locale
  - config_translation
  - content_translation
  - eca
  - eca_language
